# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'InnoTech' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for InnoTech
	source 'https://github.com/CocoaPods/Specs.git'

	pod 'AFNetworking', '~> 3.0'
	pod 'Helpshift', '5.5.1'
	pod "FBSDKCoreKit";
	pod "FBSDKLoginKit";
	pod "FBSDKShareKit";
	pod 'Firebase', '>= 2.5.1'
	pod 'Firebase/Database'
	pod 'Firebase/Crash'
	pod 'Firebase/AdMob'
	pod ‘Firebase/Auth’	
	pod 'SDWebImage/WebP'
	pod 'Firebase/RemoteConfig'
	pod 'Firebase/Messaging'
	#	pod 'mopub-ios-sdk'
end


